#!/usr/bin/env python
"""Build a robust PyMOL metal-site visualization script."""

from __future__ import annotations

import argparse
from pathlib import Path
import math


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--structure", required=True, type=Path)
    parser.add_argument("--trajectory", type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--object-name", default="product_R_md")
    parser.add_argument("--metal-selection", default="resn FE")
    parser.add_argument("--ligand-selection", default="resn LIG")
    parser.add_argument("--radius", type=float, default=4.0)
    return parser.parse_args()


def parse_gro_atoms(path: Path) -> list[dict[str, object]]:
    lines = path.read_text(errors="replace").splitlines()
    atoms = []
    for line in lines[2:-1]:
        if len(line) < 44:
            continue
        try:
            atoms.append(
                {
                    "resid": int(line[:5]),
                    "resname": line[5:10].strip(),
                    "atom": line[10:15].strip(),
                    "atomnr": int(line[15:20]),
                    "x": float(line[20:28]) * 10.0,
                    "y": float(line[28:36]) * 10.0,
                    "z": float(line[36:44]) * 10.0,
                }
            )
        except ValueError:
            continue
    return atoms


def metal_shell_residue_selection(structure: Path, radius: float) -> tuple[str, list[tuple[str, int]]]:
    atoms = parse_gro_atoms(structure)
    metals = [atom for atom in atoms if str(atom["resname"]).upper() == "FE" or str(atom["atom"]).upper() == "FE"]
    if not metals:
        return "none", []
    metal = metals[0]
    mx, my, mz = float(metal["x"]), float(metal["y"]), float(metal["z"])
    shell: dict[int, str] = {}
    for atom in atoms:
        resname = str(atom["resname"])
        if resname in {"LIG", "FE", "WAT", "SOL", "NA", "CL", "Na+", "Cl-"}:
            continue
        distance = math.dist((mx, my, mz), (float(atom["x"]), float(atom["y"]), float(atom["z"])))
        if distance <= radius:
            shell[int(atom["resid"])] = resname
    residues = [(name, resid) for resid, name in sorted(shell.items())]
    if not residues:
        return "none", []
    residue_terms = "+".join(str(resid) for _, resid in residues)
    return f"({{obj}} and not resn LIG+FE+WAT+SOL+NA+CL and resi {residue_terms})", residues


def pymol_path(path: Path) -> str:
    return str(path.resolve()).replace("\\", "/")


def main() -> None:
    args = parse_args()
    obj = args.object_name
    structure = pymol_path(args.structure)
    trajectory = pymol_path(args.trajectory) if args.trajectory else ""
    shell_template, shell_residues = metal_shell_residue_selection(args.structure, args.radius)
    shell_selection = shell_template.format(obj=obj)
    shell_comment = ", ".join(f"{name}{resid}" for name, resid in shell_residues) or "none"
    pml = f"""# Metal-site view generated by PLE.
# This script intentionally respects your pymolrc as much as possible.
load {structure}, {obj}
"""
    if trajectory:
        pml += f"load_traj {trajectory}, {obj}\n"
    pml += f"""
set retain_order, on
set ignore_case, off
set orthoscopic, on
set ray_opaque_background, off
set opaque_background, off
set bg_rgb, white
set dash_gap, 0.18
set dash_radius, 0.055
set dash_width, 2.0
set label_size, 16
set label_color, black
set cartoon_transparency, 0.35
set stick_radius, 0.16
set sphere_scale, 0.34

hide everything, all
select protein_all, {obj} and not resn LIG+FE+WAT+SOL+NA+CL
show cartoon, protein_all
color gray80, protein_all and elem C

select metal_fe, {obj} and ({args.metal_selection})
select lig, {obj} and ({args.ligand_selection})
select metal_shell_atoms, {shell_selection}
select metal_shell_sidechains, metal_shell_atoms and (sidechain or name CA)
select metal_shell_labels, metal_shell_atoms and name CA
python
print("metal_shell_atoms_count:", cmd.count_atoms("metal_shell_atoms"))
python end

show spheres, metal_fe
color tv_orange, metal_fe
show sticks, lig
color cyan, lig and elem C
show sticks, metal_shell_sidechains
color palegreen, metal_shell_sidechains and elem C

hide sticks, metal_shell_sidechains and name C+O+N
show sticks, metal_shell_sidechains and not name C+O+N
show sticks, metal_shell_sidechains and resn HID+HIE+HIP+HIS+ASP+GLU
color palegreen, metal_shell_sidechains and resn HID+HIE+HIP+HIS+ASP+GLU and elem C

# Restore default-like element colors after carbon-only recoloring.
color blue, {obj} and elem N
color red, {obj} and elem O
color yellow, {obj} and elem S
color tv_orange, metal_fe

distance fe_hid160_ne2, metal_fe, {obj} and resi 160 and resn HID+HIS and name NE2
distance fe_hid240_ne2, metal_fe, {obj} and resi 240 and resn HID+HIS and name NE2
distance fe_glu319_oe1, metal_fe, {obj} and resi 319 and resn GLU and name OE1
distance fe_lig_o_n, metal_fe, lig and elem O+N

color orange, fe_hid160_ne2
color orange, fe_hid240_ne2
color orange, fe_glu319_oe1
color yellow, fe_lig_o_n

label metal_shell_labels, "%s%s" % (resn, resi)
show labels, metal_shell_labels

select metal_site_4A, metal_shell_sidechains or lig or metal_fe
zoom metal_site_4A, 8
orient metal_site_4A

disable metal_shell_atoms
disable metal_shell_sidechains
disable metal_shell_labels
disable metal_site_4A
disable lig
disable metal_fe

# Notes:
# 1. The Fe-HID/GLU dashed lines are coordination/pseudo-bond distances.
# 2. This script intentionally avoids PyMOL's built-in show_metal helper because
#    loose selections can expand to the full protein.
# 3. Use the centered_compact trajectory to avoid PBC jumps in visualization.
# 4. Fixed Fe-shell residues from the structure: {shell_comment}
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(pml, encoding="utf-8")
    print(args.out)


if __name__ == "__main__":
    main()
